# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "ring-api"

[default.build.parameters]
cached = true
parallel = true

[dev.global.parameters]
stack_name = "ring-api-dev"

[dev.build.parameters]
cached = true
parallel = true

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ring-api-dev"
region = "eu-central-1"
disable_rollback = true
image_repositories = []
parameter_overrides = [
    "Environment=dev",
    "S3BucketName=vogelring-data-dev",
    "DynamoTableName=vogelring-dev",
    "CloudFrontDomain=dev.vogelring.com",
]

[prod.global.parameters]
stack_name = "ring-api"

[prod.build.parameters]
cached = true
parallel = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ring-api"
region = "eu-central-1"
disable_rollback = true
image_repositories = []
parameter_overrides = [
    "Environment=prod",
    "S3BucketName=vogelring-data",
    "DynamoTableName=vogelring",
    "CloudFrontDomain=vogelring.com",
]

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ring-api"
region = "eu-central-1"
disable_rollback = true
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
