AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "ring-api"

Parameters:
  RingApiKey:
    Type: String
    Description: "API Key for Ring API"
    NoEcho: true
  Environment:
    Type: String
    Description: "Environment name (dev/prod)"
    Default: prod
    AllowedValues:
      - dev
      - prod
  S3BucketName:
    Type: String
    Description: "S3 bucket name for data storage"
    Default: vogelring-data
  DynamoTableName:
    Type: String
    Description: "DynamoDB table name"
    Default: vogelring
  CloudFrontDomain:
    Type: String
    Description: "CloudFront domain"
    Default: vogelring.com
  CloudFrontKeyPairId:
    Type: String
    Description: "CloudFront key pair ID"
    Default: KTPUWAUUDMT2M
  SSMPrivateKeyParam:
    Type: String
    Description: "SSM parameter for CloudFront private key"
    Default: /vogelring/cloudfront-private-key

Globals:
  Function:
    Timeout: 20
    MemorySize: 256
    Runtime: python3.12
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Accept'"
      AllowOrigin: "'*'"
      AllowCredentials: "'true'"
    MethodSettings:
      - ThrottlingRateLimit: 2
        ThrottlingBurstLimit: 10
        MetricsEnabled: true
        ResourcePath: "/*"
        HttpMethod: "*"
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Accept'"
            Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
      DEFAULT_5XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Accept'"
            Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

Resources:
  # Writer Lambda for POST, PUT, DELETE
  RingApiWriterFunction:
    Type: AWS::Serverless::Function
    Properties:
      ReservedConcurrentExecutions: 1
      Handler: api.app.lambda_handler
      CodeUri: src
      Description: "Ring API Writer Lambda function"
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        PostRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: POST
        PutRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: PUT
        DeleteRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: DELETE
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsRingApi
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
          BUCKET: !Ref S3BucketName
          SIGHTINGS_FILE: sightings.pkl
          API_KEY: !Ref RingApiKey
          CLOUDFRONT_DOMAIN: !Ref CloudFrontDomain
          CLOUDFRONT_KEY_PAIR_ID: !Ref CloudFrontKeyPairId
          CLOUDFRONT_PRIVATE_KEY_PARAM_NAME: !Ref SSMPrivateKeyParam
          ENVIRONMENT: !Ref Environment
      Tags:
        LambdaPowertools: python
        Environment: !Ref Environment
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTableName
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SSMPrivateKeyParam}"

  # Reader Lambda for GET requests
  RingApiReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      ReservedConcurrentExecutions: 3
      Handler: api.app.lambda_handler
      CodeUri: src
      Description: "Ring API Reader Lambda function"
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
        OptionsRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: OPTIONS
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsRingApi
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
          BUCKET: !Ref S3BucketName
          SIGHTINGS_FILE: sightings.pkl
          API_KEY: !Ref RingApiKey
          CLOUDFRONT_DOMAIN: !Ref CloudFrontDomain
          CLOUDFRONT_KEY_PAIR_ID: !Ref CloudFrontKeyPairId
          CLOUDFRONT_PRIVATE_KEY_PARAM_NAME: !Ref SSMPrivateKeyParam
          ENVIRONMENT: !Ref Environment
      Tags:
        LambdaPowertools: python
        Environment: !Ref Environment
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoTableName
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SSMPrivateKeyParam}"

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

Outputs:
  Environment:
    Description: "Environment name"
    Value: !Ref Environment

  S3BucketName:
    Description: "S3 bucket name"
    Value: !Ref S3BucketName

  RingApi:
    Description: "API Gateway endpoint URL for health check"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/health"

  RingApiWriterFunction:
    Description: "Ring API Writer Lambda Function ARN"
    Value: !GetAtt RingApiWriterFunction.Arn

  RingApiReaderFunction:
    Description: "Ring API Reader Lambda Function ARN"
    Value: !GetAtt RingApiReaderFunction.Arn

  ApiGatewayUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayUrl"
