name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          # Only release the backend package
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      # Optional: Build and publish the backend package when a release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        if: ${{ steps.release.outputs.release_created }}
        uses: astral-sh/setup-uv@v3

      - name: Build backend package
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd backend
          uv build

      # Optional: Add steps here to publish to PyPI or other package registry
      # - name: Publish to PyPI
      #   if: ${{ steps.release.outputs.release_created }}
      #   run: |
      #     cd backend
      #     uv publish --token ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload build artifacts
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist/
